---
kind: Namespace
apiVersion: v1
metadata:
  name: network
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

---
kind: Namespace
apiVersion: v1
metadata:
  name: portals
  labels:
    pod-security.kubernetes.io/enforce: privileged

---
kind: Namespace
apiVersion: v1
metadata:
  name: apps
